
CREATE TABLE customer (
  id SERIAL PRIMARY KEY,
  name VARCHAR(240) NOT NULL,
  email VARCHAR(240) NOT NULL,
  mobile_number VARCHAR(10) NOT NULL,
  created_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  modified_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE accounts (
  id SERIAL PRIMARY KEY, 
  customer_id INTEGER NOT NULL,
  account_type VARCHAR(240) NOT NULL,
  branch_address VARCHAR(240) NOT NULL,
  creatad_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  modified_time TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
