ALTER TABLE accounts ADD COLUMN created_by VARCHAR(200) NOT NULL DEFAULT 'MIGT';
ALTER TABLE accounts ADD COLUMN modified_by VARCHAR(200) NOT NULL DEFAULT 'MIGT';

ALTER TABLE customer ADD COLUMN created_by VARCHAR(200) NOT NULL DEFAULT 'MIGT';
ALTER TABLE customer ADD COLUMN modified_by VARCHAR(200) NOT NULL DEFAULT 'MIGT';