services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: SpringDB
      POSTGRES_USER: tusharnagdive
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring-app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/SpringDB
      SPRING_DATASOURCE_USERNAME: tusharnagdive
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  postgres-data:
