# PORT 
server:
  port: 8003

spring:
  profiles:
    active: dev

  application:
    name: loan

  config:
    import: configserver:http://localhost:8000

  datasource:
    url: jdbc:postgresql://localhost:5432/springdb # for localhost
    # url: jdbc:postgresql://postgres:5432/springdb
    username: tusharnagdive
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.sql
    enabled: true

