services:
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: default-rabbit-1
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - tusharnagdivedev

  configserver:
    build:
      context: .
      dockerfile: Dockerfile # Specify the Dockerfile if not named 'Dockerfile'
    image: "tusharnagdivedev/configserver:v2"
    container_name: configserver-ms
    ports:
      - "8000:8000"
    platform: linux/amd64
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tusharnagdivedev

  accounts:
    image: "tusharnagdivedev/accounts:v2"
    container_name: accounts-ms
    ports:
      - "8001:8001"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tusharnagdivedev
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8000/"
      SPRING_PROFILES_ACTIVE: default

  loans:
    image: "tusharnagdivedev/loans:v2"
    container_name: loans-ms
    ports:
      - "8003:8003"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tusharnagdivedev
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8000/"
      SPRING_PROFILES_ACTIVE: default

  cards:
    image: "tusharnagdivedev/cards:v2"
    container_name: cards-ms
    ports:
      - "8002:8002"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - tusharnagdivedev
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8000/"
      SPRING_PROFILES_ACTIVE: dev

networks:
  tusharnagdivedev:
    driver: "bridge"
