services:

  eurekaserver:
    image: "tusharnagdivedev/eurekaserver:v4"
    container_name: eurekaserver-ms
    platform: linux/amd64
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "wget --spider --quiet http://localhost:8070/actuator/health || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  configserver:
    build: 
      context: .
      dockerfile: Dockerfile
    image: "tusharnagdivedev/configserver:v4"
    container_name: configserver-ms
    platform: linux/amd64
    ports:
      - "8000:8000"
    healthcheck:
      test: "curl --fail --silent localhost:8000/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "tusharnagdivedev/accounts:v4"
    container_name: accounts-ms
    ports:
      - "8001:8001"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "tusharnagdivedev/loans:v4"
    container_name: loans-ms
    ports:
      - "8003:8003"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "tusharnagdivedev/cards:v4"
    container_name: cards-ms
    ports:
      - "8002:8002"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  tusharnagdivedev:
    driver: "bridge"