version: '3.8'

services:
  app:
    image: cardswithpostgresql-app
    build:
      context: .
    ports:
      - "8002:8002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/springdb
      SPRING_DATASOURCE_USERNAME: tusharnagdive
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: springdb
      POSTGRES_USER: tusharnagdive
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
